apps/urls.py
from django.urls import include, path
from django.contrib import admin

from theme import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls', namespace='product')),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
  path('', views.product_list, name='product_list'),
  path('new', views.product_create, name='product_new'),
  path('edit/<int:pk>', views.product_update, name='product_edit'),
  path('delete/<int:pk>', views.product_delete, name='product_delete'),
]

product/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    trader_name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    mtz= models.PositiveIntegerField()
    sell14 = models.PositiveIntegerField()
    sell7 = models.PositiveIntegerField()
    ost = models.PositiveIntegerField()
    road = models.PositiveIntegerField()
    summ = models.PositiveIntegerField(default=0)

    #def save(self, *args, **kwargs):
        #if (self.summ==0):
            #self.summ = self.price + self.mtz
        #super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_edit', kwargs={'pk': self.pk})

theme/models.py
from django.db import models

# Create your models here.

apps/views.py
from django.shortcuts import render

product/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from product.models import Product
from django.utils.decorators import method_decorator
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['product_id','name', 'trader_name','price','mtz','sell14','sell7','ost','road','summ']

def product_list(request, template_name='product/product_list.html'):
    product = Product.objects.all()
    data = {}
    data['object_list'] = product
    return render(request, template_name, data)

def product_create(request, template_name='product/product_form_new.html'):
    form = ProductForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('product:product_list')
    return render(request, template_name, {'form':form})

def product_update(request, pk, template_name='product/product_form_edit.html'):
    product= get_object_or_404(Product, pk=pk)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid():
        form.save()
        return redirect('product:product_list')
    return render(request, template_name, {'form':form})

def product_delete(request, pk, template_name='product/product_confirm_delete.html'):
    product= get_object_or_404(Product, pk=pk)    
    if request.method=='POST':
        product.delete()
        return redirect('product:product_list')
    return render(request, template_name, {'object':product})

def index_view(request):
    return render(request, 'product/123.html')

theme/views.py
from django.shortcuts import render

product/templates/product/123.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>hello</p>
</body>
</html>

product/templates/product/product_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <h2><a href="{% url 'product:product_list' %}"></a>Вы действительно хотите удалить запись ?</h2>
      </li>
    </ul>
    <form  class="form-inline my-2 my-lg-0" method="post">{% csrf_token %}
      <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
  </div>
</nav>

{% endblock %}

product/templates/product/product_form_edit.html
{% extends "base.html" %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <h2><a href="{% url 'product:product_list' %}"></a>Коррекция</h2>
      </li>
    </ul>
  </div>
</nav>
<br>
<form method="post">{% csrf_token %}
  <table>
    <tr>
      <td align="right">
        Товар: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.name }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Поставщик: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.trader_name }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Учетная цена товара: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.price }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        МТЗ: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.mtz}}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Продажи за 14 дней: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.sell14}}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Продажи за 7 дней: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.sell7 }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Текущий остаток: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.ost }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Товар в пути: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.road }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Рассчет: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.summ }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
      </td>
      <td align="left">
        <button type="submit" class="btn btn-warning">Изменить</button>
      </td>
    </tr>
  <table>

</form>

{% endblock %}

product/templates/product/product_form_new.html
 <div id="bfs">


<form  class="star" method="post">{% csrf_token %}
  <table>
    <tr>
      <td align="right">
        Товар: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.name }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Поставщик: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.trader_name }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Учетная цена товара: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.price }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        МТЗ: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.mtz}}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Продажи за 14 дней: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.sell14}}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Продажи за 7 дней: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.sell7 }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Текущий остаток: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.ost }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Товар в пути: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.road }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
      </td>
      <td align="left">
        <button type="submit" class="btn btn-success">Добавить</button>
      </td>
    </tr>
  <table>
</form>
     </div>

product/templates/product/product_form_new2.html
{% extends "base.html" %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <h2><a href="{% url 'product:product_list' %}"></a>Новая запись</h2>
      </li>
    </ul>
  </div>
</nav>
<br>
<form  class="star" method="post">{% csrf_token %}
  <table>
    <tr>
      <td align="right">
        Товар: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.name }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Поставщик: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.trader_name }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Учетная цена товара: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.price }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        МТЗ: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.mtz}}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Продажи за 14 дней: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.sell14}}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Продажи за 7 дней: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.sell7 }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Текущий остаток: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.ost }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
        Товар в пути: &nbsp;&nbsp;
      </td>
      <td>
        <div class="fieldWrapper">
          {{ form.road }}
        </div>
      </td>
    </tr>
    <tr>
      <td align="right">
      </td>
      <td align="left">
        <button type="submit" class="btn btn-success">Добавить</button>
      </td>
    </tr>
  <table>


</form>

{% endblock %}

product/templates/product/product_list.html
{% extends "base.html" %}

{% block content %}
{% block javascript %}
<script type="text/javascript">
    var frm = $('#form-inline my-2 my-lg-0');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('GET'),
            url: frm.attr('{% url 'product:product_new' %}'),
            data: frm.serialize(),
            success: function (data) {
                $("#form-inline my-2 my-lg-0").html(data);
            },
            error: function(data) {
                $("#form-inline my-2 my-lg-0").html("Something went wrong!");
            }
        });
        return false;
    });
</script>
{% endblock javascript %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <form  class="form-inline my-2 my-lg-0" method="get" action="{% url 'product:product_new' %}">
          <button type="submit" class="btn btn-success">Новая поставка</button>
        </form>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" id="search" placeholder="Поиск по таблице">
    </form>
  </div>
</nav>
<div style="margin: 1%;">
<table border="2" class="table table-hover" id="mytable" cellspacing="0">
    <thead>
        <tr role="row" class="table-success">
            <th>Локальный код</th>
            <th>Товар</th>
            <th>Поставщик</th>
            <th>Учетная цена товара</th>
            <th>МТЗ</th>
            <th>Продажи за 14 дней</th>
            <th>Продажи за 7 дней</th>
            <th>Текущий остаток</th>
            <th>Товар в пути</th>
            <th>Рассчет</th>
            <th>Коррекция</th>
            <th>Удалить</th>
        </tr>
    </thead>
    <tbody>
      {% for product in object_list %}
      <tr role="row">
        <td>{{ product.product_id }} </td>
        <td> {{ product.name }}</td>
        <td> {{ product.trader_name }}</td>
        <td> {{ product.price }}</td>
        <td> {{ product.mtz }}</td>
        <td> {{ product.sell14 }} </td>
        <td> {{ product.sell7 }}</td>
        <td> {{ product.ost }}</td>
        <td> {{ product.road }} </td>
        <td> {{ product.summ }} </td>
        <td>
          <form method="get" action="{% url 'product:product_edit' product.product_id %}">
          <button type="submit" class="btn btn-warning"> Изменить</button>
          </form>
        <td>
          <form method="get" action="{% url 'product:product_delete' product.product_id %}">
          <button type="submit" class="btn btn-danger"> Удалить</button>
          </form>
      </tr>
      {% endfor %}
    </tbody>
</table>
</div>
<iframe src="{% url 'product:product_new' %}" align="center">
    Ваш браузер не поддерживает плавающие фреймы!
 </iframe>
<script>

     function rate()
{

 $.ajax({
    context: document.body,
    url: '{% url 'product:product_new' %}',
    method: 'GET',
    success: function(html){
                        $("#navbarColor03").html(html);
                    }
});

}
rate();

    </script>
{% endblock %}

theme/templates/base.html
{% load static %}

<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="{% static 'find.js' %}"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>

    <title>Автор:Хариотонова Анастасия</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div id="header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Логистика</a>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Главная <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
</body>
</html>